name: Generate Readme

on:
  schedule:
    - cron: '0 */6 * * *' # Har 6 ghante mein chalega
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Script
        run: python main.py

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add README.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto Update Stats" && git push)
          
